@startuml
class Mundo {
    - {static} instanciaMundo : Mundo = null
    - Mundo(width:int, height:int)
    + {static} GetInstance(width:int, height:int) : Mundo
    - camera : CameraOrtho
    # objetosLista : List<Objeto>
    - objetoSelecionado : ObjetoGeometria = null
    - objetoId : char = '@'
    - bBoxDesenhar : bool = false
    mouseX : int
    mouseY : int
    - objetoNovo : Poligono = null
    - indiceVerticeMaisProximo : int = 0
    - moverVerticeMaisProximo : bool = false
    - desenhandoPoligono : bool = false
    - selecionandoPoligono : bool = false
    - tipoTransformacao : int = 1
    # <<override>> OnLoad(e:EventArgs) : void
    # <<override>> OnUpdateFrame(e:FrameEventArgs) : void
    # <<override>> OnRenderFrame(e:FrameEventArgs) : void
    # <<override>> OnKeyDown(e:OpenTK.Input.KeyboardKeyEventArgs) : void
    # <<override>> OnMouseMove(e:MouseMoveEventArgs) : void
    # <<override>> OnMouseUp(e:MouseButtonEventArgs) : void
    - SelecionarPoligono() : void
    - DesenharPoligono() : void
    - Sru3D() : void
}
class Program {
    {static} Main(args:string[]) : void
}
GameWindow <|-- Mundo
@enduml
